spring:
  application:
    name: AUTH-SERVICE
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/authentication
    driverClassName: org.postgresql.Driver
    username: postgres
    password: pass
    hikari:
      auto_commit: false

logging:
  level.*:
    org.springframework.security: DEBUG
    org.springframework.web.client.RestTemplate: INFO
    com.food.recipe.api: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor: TRACE
  file:
    name: logs/auth-app.log

server:
  port: 9898